name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    if: github.actor == "B3CKDOOR"
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "We do not accept PR's on this repo. If you have any questions, join our discord."
