name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is made by specific user
        if: github.actor == 'B3CKDOOR'
        uses: superbrothers/close-pull-request@v3
        with:
        comment: "We do not accept PR's on this repo. If you have any questions, join our discord."
